import type { PlatformId } from "./inventory";

export type Region = "Champlain Valley" | "Lamoille to NEK" | "Catamount" | "Granite Capital";

export interface Dispensary {
  id: string;
  name: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  phone: string;
  website: string;
  menu_url: string;
  hours: {
    mon_fri: string;
    sat: string;
    sun: string;
  };
  tags: Array<"recreational" | "medical">;
  description: string;
  /** CRAV region/trail this dispensary belongs to. */
  region?: Region;
  /**
   * Optional transparent-background logo. Local path (e.g.
   * `/images/dispensary-logos/lake-effect-vt.png`) or a remote URL
   * approved by the site CSP `img-src` allowlist. When absent, the
   * UI falls back to a styled initial badge.
   */
  logoUrl?: string;
  /**
   * Cove Connect — which platform powers this shop's online menu, and
   * the platform-specific merchant identifier the connector uses to
   * fetch their inventory. Optional: shops without a known platform
   * are visible on CRAV but won't have live "in stock" data
   * until classified.
   */
  platform?: PlatformId;
  merchant_id?: string;
}

// Default hours used as a placeholder for the new 2026 CRAV roster
// until verified per-shop hours are imported.
const DEFAULT_HOURS = { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" };

export const dispensaries: Dispensary[] = [
  /* ── CHAMPLAIN VALLEY REGION TRAIL ── */
  {
    id: "lake-effect-vt",
    name: "Lake Effect Vt",
    address: "334 US Route 2",
    city: "South Hero",
    lat: 44.6356,
    lng: -73.3032,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Champlain Valley dispensary in South Hero on the islands. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "hello-hi",
    name: "Hello, Hi",
    address: "46 Main St Suite 102",
    city: "Winooski",
    lat: 44.4938,
    lng: -73.1851,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Winooski downtown dispensary. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "mary-jane-junction",
    name: "Mary Jane Junction",
    address: "120 Swanton Rd",
    city: "St Albans",
    lat: 44.8108,
    lng: -73.0834,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "St Albans dispensary near the Canadian border. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "milton-remedies",
    name: "Milton Remedies",
    address: "3 Southberry Dr",
    city: "Milton",
    lat: 44.6322,
    lng: -73.1117,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational", "medical"],
    description: "Milton dispensary serving both medical and adult-use customers. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "upstate-elevator",
    name: "Upstate Elevator",
    address: "699 Pine St Suite C",
    city: "Burlington",
    lat: 44.4612,
    lng: -73.2198,
    phone: "",
    website: "https://upstateelevator.com",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Pine Street Arts District dispensary with craft extracts and flower. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "the-high-bar",
    name: "The High Bar",
    address: "159 Pearl St Suite 8",
    city: "Essex Junction",
    lat: 44.4906,
    lng: -73.1108,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Essex Junction dispensary on Pearl St. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "the-bern-gallery",
    name: "The Bern Gallery",
    address: "135 Main St",
    city: "Burlington",
    lat: 44.4759,
    lng: -73.2121,
    phone: "",
    website: "https://berngallery.com",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Burlington's iconic Bern Gallery cannabis shop on Main St. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "the-herb-closet",
    name: "The Herb Closet",
    address: "196 Pearl St",
    city: "Burlington",
    lat: 44.4821,
    lng: -73.2098,
    phone: "",
    website: "https://theherbclosetvt.com",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Boutique Burlington dispensary on Pearl St. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "magic-mann",
    name: "Magic Mann",
    address: "21 Essex Way Suite 216",
    city: "Essex Junction",
    lat: 44.4906,
    lng: -73.1108,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Premium cannabis at Essex Way. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },
  {
    id: "gaston-weed-co",
    name: "Gaston Weed Co.",
    address: "100 Center Rd",
    city: "Essex Junction",
    lat: 44.4906,
    lng: -73.1108,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Essex Junction's Gaston Weed Company on Center Rd. Part of the Champlain Valley Region Trail.",
    region: "Champlain Valley",
  },

  /* ── LAMOILLE TO NEK TRAIL ── */
  {
    id: "higher-elevation",
    name: "Higher Elevation",
    address: "65 Northgate Ave Suite 6",
    city: "Morrisville",
    lat: 44.5566,
    lng: -72.5982,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Morrisville mountain-town dispensary serving the Stowe corridor. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "zenbarn-farms",
    name: "Zenbarn Farms",
    address: "1930 Waterbury-Stowe Rd",
    city: "Waterbury Center",
    lat: 44.3631,
    lng: -72.7470,
    phone: "",
    website: "https://zenbarnfarms.com",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Vermont craft cultivator and dispensary in Waterbury Center. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "good-fire-cannabis",
    name: "Good Fire Cannabis",
    address: "3627 Waterbury-Stowe Rd",
    city: "Waterbury Center",
    lat: 44.3631,
    lng: -72.7470,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Vermont Good Fire Cannabis on the road to Stowe. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "castle-cannabis",
    name: "Castle Cannabis",
    address: "853 VT-15",
    city: "Johnson",
    lat: 44.6336,
    lng: -72.6798,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Johnson Vermont dispensary on Route 15. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "kushies",
    name: "Kushies",
    address: "4267 US-5",
    city: "Derby",
    lat: 44.9555,
    lng: -72.1304,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Northeast Kingdom dispensary just south of the Canadian border. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "kingdom-kind",
    name: "Kingdom Kind",
    address: "290 Glover Rd",
    city: "Barton",
    lat: 44.7480,
    lng: -72.1773,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Northeast Kingdom Cannabis Company in Barton. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "craft-cannabis-company",
    name: "Craft Cannabis Company",
    address: "46 Hutchins St Suite 2",
    city: "Morrisville",
    lat: 44.5566,
    lng: -72.5982,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Morrisville craft cannabis dispensary. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },
  {
    id: "cambridge-cannabis-company",
    name: "Cambridge Cannabis Company",
    address: "185 Church St",
    city: "Jeffersonville",
    lat: 44.6478,
    lng: -72.8334,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Jeffersonville dispensary in the Cambridge/Smugglers' Notch area. Part of the Lamoille to NEK Trail.",
    region: "Lamoille to NEK",
  },

  /* ── THE CATAMOUNT TRAIL ── */
  {
    id: "flora-cannabis",
    name: "FLŌRA Cannabis",
    address: "2 Park St",
    city: "Middlebury",
    lat: 44.0153,
    lng: -73.1690,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Middlebury downtown dispensary on Park St. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "emerald-rose-grows",
    name: "Emerald Rose Grows",
    address: "11 Main Street",
    city: "Bristol",
    lat: 44.1338,
    lng: -73.0793,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Bristol dispensary and cultivator in the Champlain Valley foothills. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "green-mountain-therapeutics",
    name: "Green Mountain Therapeutics",
    address: "2022 N Main St",
    city: "Londonderry",
    lat: 43.2253,
    lng: -72.7973,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational", "medical"],
    description: "Londonderry dispensary near Magic Mountain. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "down-to-the-roots",
    name: "Down To The Roots",
    address: "7 Pineview Dr",
    city: "Chester",
    lat: 43.2614,
    lng: -72.5970,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Chester's Down To The Roots dispensary. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "killington-mountain-dispensary",
    name: "Killington Mountain Dispensary",
    address: "2384 Killington Rd",
    city: "Killington",
    lat: 43.6109,
    lng: -72.8101,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "On-mountain dispensary at Killington Resort. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "valley-meade",
    name: "Valley Meade",
    address: "8 VT-17",
    city: "Waitsfield",
    lat: 44.1903,
    lng: -72.8245,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Mad River Valley dispensary serving the Sugarbush corridor. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "verdiggity-organics-cannabis-company",
    name: "VerDiggity Organics Cannabis Company",
    address: "342 Depot St",
    city: "Manchester Center",
    lat: 43.1734,
    lng: -73.0726,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Manchester Center organics-focused cannabis dispensary. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "juniper-lane",
    name: "Juniper Lane",
    address: "445 Main St",
    city: "Bennington",
    lat: 42.8781,
    lng: -73.1968,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Bennington dispensary on Main St. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "mountain-girl-cannabis",
    name: "Mountain Girl Cannabis",
    address: "174 West St",
    city: "Rutland",
    lat: 43.6106,
    lng: -72.9726,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Rutland dispensary owned and operated by Vermonters. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "vermont-bud-barn",
    name: "Vermont Bud Barn",
    address: "257 Marlboro Rd",
    city: "Brattleboro",
    lat: 42.8509,
    lng: -72.5579,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Brattleboro's Vermont Bud Barn on Marlboro Rd. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "cloud-9",
    name: "Cloud 9",
    address: "87 Main St",
    city: "Fair Haven",
    lat: 43.5995,
    lng: -73.2693,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Fair Haven Cloud Nine Cannabis dispensary. Part of the Catamount Trail.",
    region: "Catamount",
  },
  {
    id: "poultney-cannabis-supplies",
    name: "Poultney Cannabis Supplies",
    address: "56 Main St",
    city: "Poultney",
    lat: 43.5181,
    lng: -73.2390,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Poultney dispensary on Main St. Part of the Catamount Trail.",
    region: "Catamount",
  },

  /* ── GRANITE CAPITAL TRAIL ── */
  {
    id: "tea-house",
    name: "Tea House",
    address: "50 Woodstock Rd",
    city: "White River Junction",
    lat: 43.6481,
    lng: -72.3192,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "White River Junction's Tea House dispensary. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "something-wicked-cannabis-company",
    name: "Something Wicked Cannabis Company",
    address: "269 Main St Riverview Unit",
    city: "Bethel",
    lat: 43.8328,
    lng: -72.6334,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Bethel's Something Wicked Cannabis Company. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "vt-strong",
    name: "VT Strong",
    address: "69 S Main St",
    city: "Barre",
    lat: 44.1976,
    lng: -72.5024,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Barre's VT Strong dispensary. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "devils-den-cannabis-co",
    name: "Devil's Den Cannabis Co.",
    address: "214 Main St Suite 420",
    city: "Bradford",
    lat: 43.9942,
    lng: -72.1276,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Bradford's Devil's Den Cannabis Co. on Main St. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "sunday-drive",
    name: "Sunday Drive",
    address: "442 Woodstock Rd Suite 3A",
    city: "Woodstock",
    lat: 43.6242,
    lng: -72.5181,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Woodstock's Sunday Drive dispensary. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "polestar-cannabis",
    name: "Polestar Cannabis",
    address: "24 Pleasant St",
    city: "Randolph",
    lat: 43.9259,
    lng: -72.6606,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Randolph's Polestar Cannabis on Pleasant St. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "forbins-reserve",
    name: "Forbins Reserve",
    address: "21 Metro Way Suite 8",
    city: "Barre",
    lat: 44.1976,
    lng: -72.5024,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Barre's Forbins Reserve dispensary. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "juanas-garden",
    name: "Juana's Garden",
    address: "188 River St",
    city: "Montpelier",
    lat: 44.2601,
    lng: -72.5754,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Montpelier's Juana's Garden on River St. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },
  {
    id: "capital-cannabis-co",
    name: "Capital Cannabis Co.",
    address: "44 Main St",
    city: "Montpelier",
    lat: 44.2601,
    lng: -72.5754,
    phone: "",
    website: "",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "Montpelier's Capital Cannabis Co. on Main St. Part of the Granite Capital Trail.",
    region: "Granite Capital",
  },

  /* ── TEST FIXTURE — used for CRAV Passport scan-flow verification ── */
  {
    id: "papa-g-dispensary",
    name: "Papa G Dispensary",
    address: "Test Location",
    city: "Burlington",
    lat: 44.4759,
    lng: -73.2121,
    phone: "",
    website: "https://covebud.com",
    menu_url: "",
    hours: DEFAULT_HOURS,
    tags: ["recreational"],
    description: "CRAV Passport test dispensary — used for development and end-to-end QR scan verification.",
    region: "Champlain Valley",
  },
];
