import type { PlatformId } from "./inventory";

export interface Dispensary {
  id: string;
  name: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  phone: string;
  website: string;
  menu_url: string;
  hours: {
    mon_fri: string;
    sat: string;
    sun: string;
  };
  tags: Array<"recreational" | "medical">;
  description: string;
  /**
   * Cove Connect — which platform powers this shop's online menu, and
   * the platform-specific merchant identifier the connector uses to
   * fetch their inventory. Optional: shops without a known platform
   * are visible on Cannatrail but won't have live "in stock" data
   * until classified.
   */
  platform?: PlatformId;
  merchant_id?: string;
}

export const dispensaries: Dispensary[] = [
  // Burlington
  {
    id: "garcias-cannabis-collective",
    name: "Garcia's Cannabis Collective",
    address: "97 Church St",
    city: "Burlington",
    lat: 44.4789,
    lng: -73.2127,
    phone: "(802) 658-5737",
    website: "https://garciascannabis.com",
    menu_url: "https://garciascannabis.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Community-rooted dispensary on Church Street with a curated selection of Vermont-grown cannabis.",
  },
  {
    id: "true-802-cannabis",
    name: "True 802 Cannabis",
    address: "132 Church St",
    city: "Burlington",
    lat: 44.4793,
    lng: -73.2133,
    phone: "(802) 540-1420",
    website: "https://true802cannabis.com",
    menu_url: "https://true802cannabis.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Burlington's premier cannabis destination with a focus on Vermont-grown, locally sourced products.",
  },
  {
    id: "lucky-you",
    name: "Lucky You",
    address: "163 Cherry St",
    city: "Burlington",
    lat: 44.4812,
    lng: -73.2051,
    phone: "(802) 448-3301",
    website: "https://luckyyouvt.com",
    menu_url: "https://luckyyouvt.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "A welcoming Burlington shop known for knowledgeable staff and a broad selection.",
  },
  {
    id: "the-herb-closet",
    name: "The Herb Closet",
    address: "196 Pearl St",
    city: "Burlington",
    lat: 44.4821,
    lng: -73.2098,
    phone: "(802) 409-3969",
    website: "https://theherbclosetvt.com",
    menu_url: "https://theherbclosetvt.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Boutique dispensary on Pearl St with an emphasis on craft Vermont cannabis.",
  },
  {
    id: "heybud-dispensary",
    name: "Heybud Dispensary",
    address: "291 Saint Paul St",
    city: "Burlington",
    lat: 44.4748,
    lng: -73.2039,
    phone: "(802) 540-0541",
    website: "https://heybudheybud.com",
    menu_url: "https://heybudheybud.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Friendly South End Burlington dispensary with a relaxed, community-first vibe.",
  },
  {
    id: "upstate-elevator",
    name: "Upstate Elevator Dispensary",
    address: "699 Pine St",
    city: "Burlington",
    lat: 44.4612,
    lng: -73.2198,
    phone: "(888) 640-2155",
    website: "https://upstateelevatorvt.com",
    menu_url: "https://upstateelevatorvt.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Pine Street Arts District dispensary with a strong lineup of craft extracts and flower.",
    platform: "dutchie",
    // TODO Day 3: confirm Dutchie slug from their embed iframe.
    merchant_id: "upstate-elevator",
  },
  // Winooski
  {
    id: "winooski-organics",
    name: "Winooski Organics",
    address: "165 E Allen St",
    city: "Winooski",
    lat: 44.4898,
    lng: -73.1854,
    phone: "(802) 899-9333",
    website: "https://winooskiorganics.com",
    menu_url: "https://winooskiorganics.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Winooski's homegrown dispensary with a focus on organic, locally-cultivated Vermont cannabis.",
  },
  // Essex Junction
  {
    id: "gaston-weed-company",
    name: "Gaston Weed Company",
    address: "100 Center Rd",
    city: "Essex Junction",
    lat: 44.4912,
    lng: -73.1148,
    phone: "(802) 494-4111",
    website: "https://gastonvt.com",
    menu_url: "https://gastonvt.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Essex Junction's go-to spot for quality Vermont cannabis in a welcoming environment.",
  },
  // South Hero
  {
    id: "lake-effect-vermont",
    name: "Lake Effect Vermont",
    address: "6 South St",
    city: "South Hero",
    lat: 44.6293,
    lng: -73.3126,
    phone: "(802) 734-2043",
    website: "https://lakeeffectvt.com",
    menu_url: "https://lakeeffectvt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 7pm", sun: "11am – 5pm" },
    tags: ["recreational", "medical"],
    description: "Island Life meets Vermont cannabis. Medical and recreational products from the shores of Lake Champlain.",
  },
  // St. Albans
  {
    id: "mothaplant",
    name: "MothaPlant",
    address: "319 Swanton Rd",
    city: "St. Albans",
    lat: 44.8117,
    lng: -73.0837,
    phone: "(802) 782-8623",
    website: "https://mothaplant.com",
    menu_url: "https://mothaplant.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Northwest Vermont's neighborhood dispensary with a down-to-earth selection and local pride.",
    platform: "tymber",
    merchant_id: "shop.mothaplant.com",
  },
  // Morrisville
  {
    id: "higher-elevation",
    name: "Higher Elevation",
    address: "65 Northgate Ave Suite 6",
    city: "Morrisville",
    lat: 44.5612,
    lng: -72.5979,
    phone: "(802) 851-8587",
    website: "https://higherelevationvt.com",
    menu_url: "https://higherelevationvt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Lamoille County's premier cannabis destination, serving the Stowe ski corridor.",
    platform: "leafly",
    merchant_id: "higher-elevation-vt",
  },
  {
    id: "freedom-flower-direct",
    name: "Freedom Flower Direct",
    address: "187 VT-15",
    city: "Morrisville",
    lat: 44.5591,
    lng: -72.5821,
    phone: "(802) 586-0031",
    website: "https://freedomflowervermont.com",
    menu_url: "https://freedomflowervermont.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Farm-direct cannabis from Vermont cultivators. Freedom Flower champions the craft grower.",
  },
  // Cambridge
  {
    id: "cambridge-cannabis-company",
    name: "Cambridge Cannabis Co.",
    address: "185 Church St",
    city: "Cambridge",
    lat: 44.6376,
    lng: -72.8781,
    phone: "(802) 899-0468",
    website: "https://cambridgecannabiscompany.com",
    menu_url: "https://cambridgecannabiscompany.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Lamoille Valley community dispensary in the shadow of the Smugglers' Notch mountains.",
  },
  // Johnson
  {
    id: "castle-cannabis",
    name: "VT Green Castle Reserve",
    address: "853 VT Route 15 West",
    city: "Johnson",
    lat: 44.6354,
    lng: -72.6781,
    phone: "(802) 696-9846",
    website: "https://vtgreencastlereserve.com",
    menu_url: "https://vtgreencastlereserve.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational", "medical"],
    description: "Serving Johnson and the Northeast Kingdom gateway with medical and recreational options.",
  },
  // Waterbury
  {
    id: "31-north",
    name: "31 North",
    address: "2653 Waterbury-Stowe Rd",
    city: "Waterbury",
    lat: 44.3376,
    lng: -72.7579,
    phone: "(802) 560-7927",
    website: "https://31northvt.com",
    menu_url: "https://31northvt.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Waterbury's cannabis corridor landmark on the road between Burlington and Stowe.",
  },
  {
    id: "zenbarn-farms",
    name: "Zenbarn Farms",
    address: "1930 Waterbury-Stowe Rd",
    city: "Waterbury Center",
    lat: 44.3512,
    lng: -72.7421,
    phone: "(802) 244-8134",
    website: "https://zenbarnmj.com",
    menu_url: "https://zenbarnmj.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "A Vermont institution. Zenbarn blends farm culture with craft cannabis in the heart of the state.",
  },
  // Montpelier
  {
    id: "capital-cannabis-co",
    name: "Capital Cannabis Co.",
    address: "44 Main St",
    city: "Montpelier",
    lat: 44.2601,
    lng: -72.5754,
    phone: "(802) 505-5663",
    website: "https://capitalcannabisvt.com",
    menu_url: "https://capitalcannabisvt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "12pm – 5pm" },
    tags: ["recreational", "medical"],
    description: "The capital's flagship dispensary with a full spectrum of medical and recreational products.",
  },
  {
    id: "juanas-garden",
    name: "Juana's Garden",
    address: "188 River St",
    city: "Montpelier",
    lat: 44.2576,
    lng: -72.5721,
    phone: "(802) 917-1009",
    website: "https://juanasgarden.net",
    menu_url: "https://juanasgarden.net",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "12pm – 5pm" },
    tags: ["recreational"],
    description: "Montpelier's neighborhood garden of cannabis delights — knowledgeable, welcoming, Vermont-rooted.",
  },
  // Barre
  {
    id: "forbins-reserve",
    name: "Forbins Reserve",
    address: "21 Metro Way Ste 8",
    city: "Barre",
    lat: 44.1970,
    lng: -72.5021,
    phone: "(802) 622-0359",
    website: "https://forbinsfinest.com",
    menu_url: "https://forbinsfinest.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Granite City's finest cannabis from Vermont's granite country, curated for quality.",
  },
  // Danville
  {
    id: "the-bud-stop",
    name: "The Bud Stop",
    address: "1513 US Rte 2",
    city: "Danville",
    lat: 44.4126,
    lng: -72.1154,
    phone: "(802) 265-5910",
    website: "https://thebudstop.store",
    menu_url: "https://thebudstop.store",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Northeast Kingdom entry point — friendly, well-stocked, and rooted in the Kingdom community.",
  },
  // Montgomery Center
  {
    id: "mary-jane-mountain",
    name: "Mary Jane Mountain",
    address: "91 Main St",
    city: "Montgomery Center",
    lat: 44.8876,
    lng: -72.6354,
    phone: "(802) 326-2006",
    website: "https://maryjanemountainvt.com",
    menu_url: "https://maryjanemountainvt.com",
    hours: { mon_fri: "10am – 6pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Northern Vermont's mountain-town dispensary serving the Jay Peak ski community.",
  },
  // Saint Johnsbury
  {
    id: "northeast-kannabis",
    name: "Northeast Kannabis",
    address: "166 Railroad St",
    city: "Saint Johnsbury",
    lat: 44.4187,
    lng: -72.0154,
    phone: "(802) 424-1760",
    website: "https://northeastkannabis.com",
    menu_url: "https://northeastkannabis.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 7pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "The Northeast Kingdom's anchor dispensary — wide selection, local knowledge, Kingdom proud.",
  },
  // Derby
  {
    id: "kingdom-boyz-cannabis",
    name: "Kingdom Boyz Cannabis",
    address: "3731 US-5",
    city: "Derby",
    lat: 44.9543,
    lng: -72.1054,
    phone: "(802) 766-3520",
    website: "https://kingdomboyzvt.com",
    menu_url: "https://kingdomboyzvt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Far north Vermont's Kingdom-grown cannabis outpost, steps from the Canadian border.",
  },
  // Waitsfield
  {
    id: "blue-sage",
    name: "Blue Sage",
    address: "5121 Main St",
    city: "Waitsfield",
    lat: 44.1876,
    lng: -72.8254,
    phone: "(802) 583-2193",
    website: "https://bluesagevt.com",
    menu_url: "https://bluesagevt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational", "medical"],
    description: "Mad River Valley's wellness-forward cannabis destination — recreational and medical in the ski corridor.",
  },
  // Randolph
  {
    id: "polestar-cannabis",
    name: "Polestar Cannabis",
    address: "24 Pleasant St",
    city: "Randolph",
    lat: 43.9276,
    lng: -72.6554,
    phone: "(802) 565-5168",
    website: "https://polestarvt.com",
    menu_url: "https://polestarvt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Central Vermont's guiding light for craft cannabis — genuine, local, and community-rooted.",
  },
  // White River Junction
  {
    id: "the-tea-house",
    name: "The Tea House",
    address: "50 Woodstock Rd",
    city: "White River Junction",
    lat: 43.6487,
    lng: -72.3154,
    phone: "(802) 332-6043",
    website: "https://teahousevt.com",
    menu_url: "https://teahousevt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational", "medical"],
    description: "Upper Valley's calm cannabis sanctuary — thoughtful product curation with medical expertise.",
  },
  // Woodstock
  {
    id: "sunday-drive",
    name: "Sunday Drive",
    address: "442 Woodstock Rd Suite 3A",
    city: "Woodstock",
    lat: 43.6243,
    lng: -72.5217,
    phone: "(802) 332-0049",
    website: "https://vtsundaydrive.com",
    menu_url: "https://vtsundaydrive.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Take the Sunday Drive into Woodstock's premier cannabis shop — unhurried, quality-focused, Vermont-proud.",
  },
  // Middlebury
  {
    id: "flora-cannabis",
    name: "FLŌRA Cannabis",
    address: "2 Park St",
    city: "Middlebury",
    lat: 44.0148,
    lng: -73.1679,
    phone: "(802) 989-7948",
    website: "https://floravt.com",
    menu_url: "https://floravt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Addison County's blooming cannabis boutique — beautifully curated, locally grown, naturally yours.",
    // Platform discovered Day 3, but our Dutchie connector is on hold:
    // dutchie.com gates GraphQL behind Cloudflare and the operator
    // subdomain (shop.floravt.com) is a SPA shell. Reach blocked
    // until we add Playwright or get Dutchie API access.
    platform: "dutchie",
    merchant_id: "62f28802b87e0f676aeaa8a6", // dispensary id from embed bootstrap
  },
  {
    id: "the-herbal-collective",
    name: "The Herbal Collective",
    address: "1641 US-7",
    city: "Middlebury",
    lat: 44.0098,
    lng: -73.1712,
    phone: "(802) 377-2124",
    website: "https://theherbalcollectivevt.com",
    menu_url: "https://theherbalcollectivevt.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational", "medical"],
    description: "Full-spectrum cannabis care in the Champlain Valley — medical and recreational with deep product knowledge.",
  },
  // Vergennes
  {
    id: "little-city-greens",
    name: "Little City Greens",
    address: "7 Green St",
    city: "Vergennes",
    lat: 44.1676,
    lng: -73.2554,
    phone: "(802) 870-7729",
    website: "https://littlecitygreens.com",
    menu_url: "https://littlecitygreens.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Vermont's smallest city, biggest heart — Vergennes' neighborhood cannabis shop.",
  },
  // Bristol
  {
    id: "emeraldrose-grows",
    name: "Emeraldrose Grows",
    address: "11 Main St",
    city: "Bristol",
    lat: 44.1326,
    lng: -73.0754,
    phone: "(802) 453-4797",
    website: "https://emeraldrosegrows.com",
    menu_url: "https://emeraldrosegrows.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Green Mountain foothills dispensary with a cultivator-first ethos and Vermont-grown selection.",
  },
  // Rutland
  {
    id: "somewhere-on-the-mountain",
    name: "Somewhere on the Mountain",
    address: "158 N Main St",
    city: "Rutland",
    lat: 43.6106,
    lng: -72.9726,
    phone: "(802) 776-4447",
    website: "https://somewhereonthemountain.com",
    menu_url: "https://somewhereonthemountain.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Rutland's elevated cannabis experience — serving Vermont's second city with mountain-high quality.",
  },
  // Brandon
  {
    id: "pine-grove-organics",
    name: "Pine Grove Organics",
    address: "16 Park St",
    city: "Brandon",
    lat: 43.7976,
    lng: -73.0854,
    phone: "(802) 265-0136",
    website: "https://pinegroveorganics.org",
    menu_url: "https://pinegroveorganics.org",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Organic-first cannabis from Vermont's most committed cultivator-retail team in Brandon.",
  },
  // Bradford
  {
    id: "devils-den-cannabis",
    name: "Devil's Den Cannabis Co.",
    address: "214 Main St Suite 420",
    city: "Bradford",
    lat: 43.9943,
    lng: -72.1354,
    phone: "(802) 449-3119",
    website: "https://devilsdencannabis.com",
    menu_url: "https://devilsdencannabis.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Connecticut River Valley's boldest cannabis shop — unforgettable name, exceptional product.",
  },
  // Springfield
  {
    id: "the-buddega",
    name: "The Buddega",
    address: "10 Clinton St",
    city: "Springfield",
    lat: 43.2976,
    lng: -72.4854,
    phone: "(802) 885-6705",
    website: "https://thebuddega.com",
    menu_url: "https://thebuddega.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Southern Vermont's corner bodega for cannabis — stocked, friendly, and community-driven.",
  },
  // Brattleboro
  {
    id: "vt-bud-barn",
    name: "VT Bud Barn",
    address: "257 Marlboro Rd Suite 101",
    city: "Brattleboro",
    lat: 42.8509,
    lng: -72.5579,
    phone: "(802) 246-4367",
    website: "https://vtbudbarn.com",
    menu_url: "https://vtbudbarn.com",
    hours: { mon_fri: "10am – 8pm", sat: "10am – 8pm", sun: "11am – 6pm" },
    tags: ["recreational"],
    description: "Brattleboro's barn full of Vermont's best — flower, concentrates, and edibles from local growers.",
  },
  {
    id: "theory-wellness-brattleboro",
    name: "Theory Wellness",
    address: "768 Putney Rd",
    city: "Brattleboro",
    lat: 42.8621,
    lng: -72.5487,
    phone: "(802) 454-3480",
    website: "https://theorywellness.org",
    menu_url: "https://theorywellness.org",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Science-forward cannabis wellness in the Connecticut River Valley — thoughtful, quality-driven.",
  },
  // Barton
  {
    id: "kingdom-kind",
    name: "Kingdom Kind",
    address: "290 Glover Rd",
    city: "Barton",
    lat: 44.7543,
    lng: -72.1754,
    phone: "(802) 243-4367",
    website: "https://nekkind.com",
    menu_url: "https://nekkind.com",
    hours: { mon_fri: "10am – 7pm", sat: "10am – 6pm", sun: "11am – 5pm" },
    tags: ["recreational"],
    description: "Northeast Kingdom kindness in every visit — local growers, local faces, local love.",
  },
];
