export interface Strain {
  id: string;
  name: string;
  type: "Indica" | "Sativa" | "Hybrid";
  thc: string;
  cbd: string;
  effects: string[];
  terpenes: string[];
  flavors: string[];
  description: string;
}

export const strains: Strain[] = [
  {
    id: "blue-dream",
    name: "Blue Dream",
    type: "Hybrid",
    thc: "17–24%",
    cbd: "0.1–0.2%",
    effects: ["Euphoric", "Creative", "Uplifted", "Relaxed", "Happy"],
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    flavors: ["Blueberry", "Sweet", "Herbal"],
    description: "A California classic that crosses Blueberry Indica with Sativa Haze. Blue Dream delivers a gentle cerebral invigoration alongside full-body relaxation — a daytime favorite for creatives and those managing pain or fatigue.",
  },
  {
    id: "gorilla-glue-4",
    name: "Gorilla Glue #4",
    type: "Hybrid",
    thc: "25–30%",
    cbd: "0.1%",
    effects: ["Relaxed", "Euphoric", "Sleepy", "Happy", "Uplifted"],
    terpenes: ["Caryophyllene", "Myrcene", "Limonene"],
    flavors: ["Earthy", "Pine", "Sour", "Chocolate"],
    description: "A potent hybrid that glues you to the couch with heavy-handed euphoria. GG4 took home multiple Cannabis Cup wins and remains a benchmark for resin production. Best for evening use.",
  },
  {
    id: "wedding-cake",
    name: "Wedding Cake",
    type: "Indica",
    thc: "22–25%",
    cbd: "0.1%",
    effects: ["Relaxed", "Euphoric", "Happy", "Uplifted", "Tingly"],
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    flavors: ["Sweet", "Vanilla", "Earthy", "Pepper"],
    description: "A rich and tangy Indica-dominant hybrid with a complex terpene profile. Wedding Cake produces a euphoric high that relaxes both body and mind — popular for stress, pain, and insomnia.",
  },
  {
    id: "sour-diesel",
    name: "Sour Diesel",
    type: "Sativa",
    thc: "18–26%",
    cbd: "0.2%",
    effects: ["Energetic", "Euphoric", "Creative", "Uplifted", "Happy"],
    terpenes: ["Caryophyllene", "Myrcene", "Limonene"],
    flavors: ["Diesel", "Citrus", "Earthy", "Skunky"],
    description: "A fast-acting Sativa celebrated for its dreamy, cerebral effects. Sour Diesel's pungent fuel aroma and energizing high make it a go-to for depression, pain, and stress. Vermont cultivators grow it well in the Northeast climate.",
  },
  {
    id: "og-kush",
    name: "OG Kush",
    type: "Hybrid",
    thc: "19–26%",
    cbd: "0.3%",
    effects: ["Euphoric", "Relaxed", "Happy", "Uplifted", "Sleepy"],
    terpenes: ["Myrcene", "Limonene", "Caryophyllene"],
    flavors: ["Earthy", "Pine", "Woody", "Lemon"],
    description: "The foundation of many West Coast strains. OG Kush delivers a heavy, complex high blending euphoria with deep relaxation. A benchmark strain for hybrid breeding — the parent of dozens of modern classics.",
  },
  {
    id: "gelato",
    name: "Gelato",
    type: "Hybrid",
    thc: "20–25%",
    cbd: "0.1%",
    effects: ["Euphoric", "Happy", "Relaxed", "Creative", "Uplifted"],
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    flavors: ["Sweet", "Berry", "Citrus", "Lavender"],
    description: "A dessert strain born from Sunset Sherbet and Thin Mint GSC. Gelato hits fast with a cerebral rush before settling into full-body relaxation. The sweet, creamy terpene profile makes it one of the most enjoyable smoke experiences.",
  },
  {
    id: "northern-lights",
    name: "Northern Lights",
    type: "Indica",
    thc: "16–21%",
    cbd: "0.1%",
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    flavors: ["Earthy", "Sweet", "Pine", "Spicy"],
    description: "One of the most legendary Indicas ever bred. Northern Lights wraps the body in a warm, numbing relaxation while the mind drifts into quiet euphoria. A classic strain for insomnia, pain, and anxiety.",
  },
  {
    id: "jack-herer",
    name: "Jack Herer",
    type: "Sativa",
    thc: "15–24%",
    cbd: "0.1%",
    effects: ["Energetic", "Creative", "Happy", "Uplifted", "Focused"],
    terpenes: ["Terpinolene", "Caryophyllene", "Ocimene"],
    flavors: ["Earthy", "Pine", "Woody", "Citrus"],
    description: "Named for the cannabis activist and author of 'The Emperor Wears No Clothes.' Jack Herer blends a blissful, clear-headed high with creative energy. A spicy, pine-scented Sativa perfect for daytime use.",
  },
  {
    id: "zkittlez",
    name: "Zkittlez",
    type: "Indica",
    thc: "15–23%",
    cbd: "0.5%",
    effects: ["Relaxed", "Happy", "Euphoric", "Uplifted", "Focused"],
    terpenes: ["Caryophyllene", "Humulene", "Linalool"],
    flavors: ["Grape", "Berry", "Tropical", "Sweet"],
    description: "Taste the rainbow with this award-winning Indica blend. Zkittlez delivers a wave of fruit-forward flavors and a calming, mood-lifting high. A strain that can be enjoyed any time of day without overwhelming sedation.",
  },
  {
    id: "mac-1",
    name: "MAC 1",
    type: "Hybrid",
    thc: "22–28%",
    cbd: "0.1%",
    effects: ["Euphoric", "Relaxed", "Happy", "Creative", "Energetic"],
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    flavors: ["Floral", "Citrus", "Earthy", "Creamy"],
    description: "Miracle Alien Cookies #1 — a cultivar that has taken the craft cannabis world by storm. MAC 1 is prized for its dense, resin-drenched buds and a balanced, versatile high that appeals to both recreational and medical users.",
  },
  {
    id: "durban-poison",
    name: "Durban Poison",
    type: "Sativa",
    thc: "15–20%",
    cbd: "0.2%",
    effects: ["Energetic", "Uplifted", "Creative", "Focused", "Happy"],
    terpenes: ["Terpinolene", "Myrcene", "Ocimene"],
    flavors: ["Sweet", "Earthy", "Pine", "Anise"],
    description: "A pure landrace Sativa from South Africa. Durban Poison's uplifting and energetic effects make it the espresso of cannabis — clean, clear, and focused. One of the best strains for productivity and outdoor activities.",
  },
  {
    id: "purple-punch",
    name: "Purple Punch",
    type: "Indica",
    thc: "18–20%",
    cbd: "0.1%",
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    terpenes: ["Caryophyllene", "Myrcene", "Pinene"],
    flavors: ["Grape", "Blueberry", "Vanilla", "Candy"],
    description: "A delicious Indica cross of Larry OG and Granddaddy Purple. Purple Punch is a knockout after-dinner strain — deeply relaxing with a sweet grape and blueberry flavor profile. Excellent for sleep and pain management.",
  },
  {
    id: "runtz",
    name: "Runtz",
    type: "Hybrid",
    thc: "19–29%",
    cbd: "0.1%",
    effects: ["Euphoric", "Relaxed", "Happy", "Uplifted", "Tingly"],
    terpenes: ["Caryophyllene", "Limonene", "Linalool"],
    flavors: ["Candy", "Tropical", "Sweet", "Berry"],
    description: "A celebrity strain born from Zkittlez and Gelato. Runtz delivers long-lasting euphoria and relaxation with a candy-sweet flavor that made it one of the most sought-after strains of the 2020s.",
  },
  {
    id: "granddaddy-purple",
    name: "Granddaddy Purple",
    type: "Indica",
    thc: "17–23%",
    cbd: "0.1%",
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    flavors: ["Grape", "Berry", "Sweet", "Earthy"],
    description: "Ken Estes' flagship Indica, a cross of Purple Urkle and Big Bud. GDP is celebrated for its vibrant purple hues and a powerful, grape-scented high that locks you into the couch. A top choice for pain, insomnia, and appetite loss.",
  },
  {
    id: "green-crack",
    name: "Green Crack",
    type: "Sativa",
    thc: "15–25%",
    cbd: "0.1%",
    effects: ["Energetic", "Focused", "Creative", "Uplifted", "Happy"],
    terpenes: ["Myrcene", "Caryophyllene", "Ocimene"],
    flavors: ["Mango", "Citrus", "Earthy", "Sweet"],
    description: "Named by Snoop Dogg for its sharp, invigorating energy. Green Crack delivers a tangy mango flavor and a racy, focused high. A pure Sativa experience ideal for daytime tasks, creative projects, or outdoor adventures.",
  },
  {
    id: "white-widow",
    name: "White Widow",
    type: "Hybrid",
    thc: "18–25%",
    cbd: "0.2%",
    effects: ["Euphoric", "Energetic", "Creative", "Happy", "Uplifted"],
    terpenes: ["Myrcene", "Caryophyllene", "Pinene"],
    flavors: ["Earthy", "Woody", "Floral", "Pepper"],
    description: "A Dutch classic that has been a coffeehouse staple since the 1990s. White Widow's balanced hybrid effects — energizing euphoria followed by relaxed contentment — have made it a global benchmark for over three decades.",
  },
  {
    id: "chemdawg",
    name: "Chemdawg",
    type: "Hybrid",
    thc: "15–20%",
    cbd: "0.1%",
    effects: ["Euphoric", "Creative", "Relaxed", "Happy", "Uplifted"],
    terpenes: ["Caryophyllene", "Myrcene", "Limonene"],
    flavors: ["Diesel", "Chemical", "Earthy", "Pine"],
    description: "The mysterious ancestor of OG Kush and Sour Diesel. Chemdawg's pungent diesel aroma and cerebral, thought-provoking high have cemented its legendary status. A strain for experienced users seeking a strong, complex experience.",
  },
  {
    id: "pineapple-express",
    name: "Pineapple Express",
    type: "Hybrid",
    thc: "17–25%",
    cbd: "0.1%",
    effects: ["Energetic", "Creative", "Happy", "Uplifted", "Euphoric"],
    terpenes: ["Caryophyllene", "Ocimene", "Myrcene"],
    flavors: ["Pineapple", "Mango", "Cedar", "Citrus"],
    description: "The strain that launched a thousand memes. Beyond the pop culture status, Pineapple Express is a genuinely excellent Sativa-dominant hybrid — tropical flavors, a productive buzz, and long-lasting effects that inspire creativity.",
  },
  {
    id: "gelato-41",
    name: "Gelato 41",
    type: "Hybrid",
    thc: "20–26%",
    cbd: "0.1%",
    effects: ["Euphoric", "Relaxed", "Happy", "Uplifted", "Creative"],
    terpenes: ["Caryophyllene", "Limonene", "Linalool"],
    flavors: ["Sweet", "Citrus", "Berry", "Lavender"],
    description: "The phenotype of Gelato that took the cannabis world by storm. Gelato 41 is renowned for its exceptional resin production and a perfectly balanced high — uplifting and creative at first, melting into a warm body relaxation.",
  },
  {
    id: "lemon-haze",
    name: "Lemon Haze",
    type: "Sativa",
    thc: "17–25%",
    cbd: "0.2%",
    effects: ["Energetic", "Happy", "Uplifted", "Creative", "Focused"],
    terpenes: ["Terpinolene", "Ocimene", "Myrcene"],
    flavors: ["Lemon", "Citrus", "Sweet", "Earthy"],
    description: "A bright, citrus-forward Sativa with a sparkling lemon aroma. Lemon Haze provides an uplifting, alert high perfect for social situations, outdoor activities, or creative work. Popular in Vermont's growing community.",
  },
  {
    id: "forbidden-fruit",
    name: "Forbidden Fruit",
    type: "Indica",
    thc: "18–26%",
    cbd: "0.1%",
    effects: ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
    terpenes: ["Myrcene", "Caryophyllene", "Linalool"],
    flavors: ["Cherry", "Tropical", "Citrus", "Earthy"],
    description: "A cross of Cherry Pie and Tangie that smells exactly like its name. Forbidden Fruit delivers deeply physical Indica effects layered under a complex tropical and cherry terpene profile. Best enjoyed in the evening.",
  },
  {
    id: "blue-dragon",
    name: "Blue Dragon",
    type: "Hybrid",
    thc: "14–20%",
    cbd: "0.5%",
    effects: ["Relaxed", "Happy", "Euphoric", "Creative", "Uplifted"],
    terpenes: ["Myrcene", "Pinene", "Caryophyllene"],
    flavors: ["Blueberry", "Floral", "Earthy", "Sweet"],
    description: "A beloved Vermont craft strain — Blue Dragon crosses Blueberry with Sour Diesel to produce a balanced hybrid with a distinctive blueberry and floral aroma. Locally grown in the Green Mountains and a Cannatrail favorite.",
  },
  {
    id: "strawberry-cough",
    name: "Strawberry Cough",
    type: "Sativa",
    thc: "15–20%",
    cbd: "0.5%",
    effects: ["Uplifted", "Happy", "Energetic", "Creative", "Focused"],
    terpenes: ["Myrcene", "Caryophyllene", "Ocimene"],
    flavors: ["Strawberry", "Berry", "Sweet", "Earthy"],
    description: "A mysterious Sativa known for its sweet strawberry scent and a cough-inducing thick smoke. Strawberry Cough provides an uplifting, social high that eases anxiety while keeping you mentally clear and energized.",
  },
  {
    id: "animal-cookies",
    name: "Animal Cookies",
    type: "Indica",
    thc: "22–27%",
    cbd: "0.1%",
    effects: ["Relaxed", "Euphoric", "Happy", "Sleepy", "Hungry"],
    terpenes: ["Caryophyllene", "Limonene", "Myrcene"],
    flavors: ["Sweet", "Vanilla", "Earthy", "Sour"],
    description: "A cross of Fire OG and Girl Scout Cookies. Animal Cookies produces full-body relaxation and euphoria with a sweet, sour aroma. A high-potency Indica for experienced consumers seeking deep stress and pain relief.",
  },
  {
    id: "tropicana-cookies",
    name: "Tropicana Cookies",
    type: "Sativa",
    thc: "20–25%",
    cbd: "0.1%",
    effects: ["Euphoric", "Energetic", "Creative", "Happy", "Uplifted"],
    terpenes: ["Limonene", "Caryophyllene", "Linalool"],
    flavors: ["Orange", "Citrus", "Sweet", "Tropical"],
    description: "A Sativa-dominant cross of Girl Scout Cookies and Tangie. Tropicana Cookies bursts with orange citrus aromas and delivers an uplifting, creative high. A modern classic from the craft cannabis scene.",
  },
];
